version: '3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'nexign-postgres'
    ports:
      - "5432:5432"
    environment:
      - 'PGUSER=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=security-service'
  service-discovery:
    container_name: 'service-discovery'
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
  api-gateway:
    container_name: 'api-gateway'
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - 'service-discovery'
  demo-service:
    container_name: 'demo-service'
    build:
      context: ./demo-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - 'api-gateway'
  security-service:
    container_name: 'security-service'
    build:
      context: ./security-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - 'api-gateway'