eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082

spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/security-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: security-service

jwt:
  secret:
    access:
      key: B6E5061FADAD40CCAEBDD0F4B3EB3DEE3F4FCE86695FA0076BA9E0A894A53140
      expiration: 1000

---

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

spring:
  config:
    activate:
      on-profile: docker